# Distribution-specific variables for Ubuntu.
# Loaded automatically by tasks/main.yml via first_found lookup.
---
samba_dc_packages:
  - samba-ad-dc
  - smbclient
  - krb5-user
  - bind9-dnsutils
  - acl
  - attr
  - ntpsec
samba_dc_service: samba-ad-dc
samba_dc_mask_services:
  - smbd
  - nmbd
  - winbind
samba_ntp_service: ntpsec
samba_ntp_conf: /etc/ntpsec/ntp.conf
samba_ntp_driftfile: /var/lib/ntpsec/ntp.drift
samba_ntp_group: ntpsec
samba_statedir: /var/lib/samba
