# Distribution-specific variables for Ubuntu.
# Loaded automatically by tasks/main.yml via first_found lookup.
---
samba_dc_packages:
  - samba-ad-dc
  - smbclient
  - krb5-user
  - bind9-dnsutils
  - acl
  - attr
  - ldb-tools
  - nfs-kernel-server
  - nfs-common
samba_dc_service: samba-ad-dc
samba_dc_mask_services:
  - smbd
  - nmbd
  - winbind
samba_statedir: /var/lib/samba
